[package]
name = "rtrpc_client"
version = "0.1.0"
authors = ["Ben Pig Chu <benpichu@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
bytes = "0.4"
rtrpc_common = { path = "../rtrpc_common" }
